version: '3.8'

services:
  redis-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-master
    networks:
      redis-net:
        ipv4_address: 172.28.0.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

  redis-slave1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-slave1
    networks:
      redis-net:
        ipv4_address: 172.28.0.3
    ports:
      - "6380:6379"
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

  redis-slave2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-slave2
    networks:
      redis-net:
        ipv4_address: 172.28.0.4
    ports:
      - "6381:6379"
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

  redis-slave3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-slave3
    networks:
      redis-net:
        ipv4_address: 172.28.0.5
    ports:
      - "6382:6379"
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always

  sentinel1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-sentinel1
    networks:
      redis-net:
        ipv4_address: 172.28.0.6
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    restart: always

  sentinel2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-sentinel2
    networks:
      redis-net:
        ipv4_address: 172.28.0.7
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    restart: always

  sentinel3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-sentinel3
    networks:
      redis-net:
        ipv4_address: 172.28.0.8
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    restart: always

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
