version: '3.8'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpleredis
    image: redis-no-persistance
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]